apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: spring-petclinic-config
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - MYSQL_URL=jdbc:mysql://mysql:3306/petclinic

secretGenerator:
  - name: spring-boot-secret
    literals:
      - database-user=petclinic
      - database-password=petclinic

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-petclinic
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: spring-boot-app
              image: quay.io/williamsrlin/spring-petclinic:1.0.0
